export const TAU=Math.PI*2, MONO='"DejaVu Sans Mono", Consolas, "Liberation Mono", monospace';
export type Ctx=CanvasRenderingContext2D;
export type Rect={x:number;y:number;w:number;h:number};
export type Paint=string|CanvasGradient|CanvasPattern;
export type Region={id:string;rects:Rect[];pixelRects:Rect[]};
export type Frame={kind:string;note:string;dataUrl:string;W:number;H:number;targets:Region[];seals:Region[]};
export type SensorOpts={scale?:number;noise?:number;scan?:number;bleed?:number;tear?:boolean;seed?:number;vignettePower?:number};
export function mk(W:number,H:number):[HTMLCanvasElement,Ctx]{const c=document.createElement('canvas');c.width=W;c.height=H;return [c,c.getContext('2d',{willReadFrequently:true})!];}
export function rng(seed:number):()=>number{return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
export function rect(x:Ctx,X:number,Y:number,W:number,H:number,color:Paint){x.fillStyle=color;x.fillRect(X,Y,W,H);}
export function poly(x:Ctx,pts:[number,number][],color:Paint){x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.closePath();x.fillStyle=color;x.fill();}
export function line(x:Ctx,pts:[number,number][],color:Paint,width=1){x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.strokeStyle=color;x.lineWidth=width;x.stroke();}
export function ellipse(x:Ctx,X:number,Y:number,RX:number,RY:number,color:Paint){x.beginPath();x.ellipse(X,Y,RX,RY,0,0,TAU);x.fillStyle=color;x.fill();}
export function grad(x:Ctx,x0:number,y0:number,x1:number,y1:number,stops:[number,string][]){const g=x.createLinearGradient(x0,y0,x1,y1);stops.forEach(p=>g.addColorStop(p[0],p[1]));return g;}
export function glow(x:Ctx,X:number,Y:number,R:number,color:string,power=1){x.save();x.globalCompositeOperation='screen';x.globalAlpha=power;const g=x.createRadialGradient(X,Y,0,X,Y,R);g.addColorStop(0,color);g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(X-R,Y-R,R*2,R*2);x.restore();}
export function txt(x:Ctx,s:string,X:number,Y:number,size:number,color:string='#d8e6df',weight:string='400',align:CanvasTextAlign='left'){x.font=`${weight} ${size}px ${MONO}`;x.textAlign=align;x.textBaseline='alphabetic';x.fillStyle=color;x.fillText(s,X,Y);}
export function textBox(x:Ctx,s:string,X:number,Y:number,size:number,color:string,weight:string='400',align:CanvasTextAlign='left'):Rect{txt(x,s,X,Y,size,color,weight,align);const m=x.measureText(s);const l=Math.floor(X-m.actualBoundingBoxLeft),t=Math.floor(Y-m.actualBoundingBoxAscent),r=Math.ceil(X+m.actualBoundingBoxRight),b=Math.ceil(Y+m.actualBoundingBoxDescent);return {x:l,y:t,w:r-l,h:b-t};}
export function bounds(ctx:Ctx):Rect{const {width:W,height:H}=ctx.canvas,d=ctx.getImageData(0,0,W,H).data;let l=W,t=H,r=-1,b=-1;for(let y=0;y<H;y++)for(let X=0;X<W;X++)if(d[(y*W+X)*4+3]){l=Math.min(l,X);r=Math.max(r,X);t=Math.min(t,y);b=Math.max(b,y);}if(r<0)throw Error('Empty region layer');return {x:l,y:t,w:r-l+1,h:b-t+1};}
export function layer(x:Ctx,draw:(k:Ctx)=>void):Rect{const [c,k]=mk(x.canvas.width,x.canvas.height);draw(k);const b=bounds(k);x.drawImage(c,0,0);return b;}
export function subtract(a:Rect,b:Rect):Rect[]{const l=Math.max(a.x,b.x),t=Math.max(a.y,b.y),r=Math.min(a.x+a.w,b.x+b.w),d=Math.min(a.y+a.h,b.y+b.h);if(l>=r||t>=d)return[a];return[{x:a.x,y:a.y,w:a.w,h:t-a.y},{x:a.x,y:d,w:a.w,h:a.y+a.h-d},{x:a.x,y:t,w:l-a.x,h:d-t},{x:r,y:t,w:a.x+a.w-r,h:d-t}].filter(q=>q.w>0&&q.h>0);}
export function region(id:string,boxes:Rect|Rect[],W:number,H:number):Region{const arr=Array.isArray(boxes)?boxes:[boxes];return{id,rects:arr.map(b=>({x:b.x/W,y:b.y/H,w:b.w/W,h:b.h/H})),pixelRects:arr};}
export function finish(c:HTMLCanvasElement,kind:string,note:string,targets:[string,Rect|Rect[]][],seals:[string,Rect|Rect[]][]):Frame{const W=c.width,H=c.height;return{kind,note,dataUrl:c.toDataURL('image/png'),W,H,targets:targets.map(([id,b])=>region(id,b,W,H)),seals:seals.map(([id,b])=>region(id,b,W,H))};}
export function grain(x:Ctx,W:number,H:number,amount:number){const a=x.getImageData(0,0,W,H),d=a.data;for(let i=0;i<d.length;i+=4){const luminance=(d[i]+d[i+1]+d[i+2])/765;const n=(Math.random()+Math.random()-1)*amount*(1-.45*luminance);d[i]+=n;d[i+1]+=n*.9;d[i+2]+=n*1.08;}x.putImageData(a,0,0);}
function vignette(x:Ctx,W:number,H:number,strength:number){const g=x.createRadialGradient(W*.51,H*.46,H*.12,W*.5,H*.5,W*.66);g.addColorStop(0,'#0000');g.addColorStop(.65,'rgba(0,0,0,.08)');g.addColorStop(1,`rgba(0,0,0,${strength})`);x.fillStyle=g;x.fillRect(0,0,W,H);}
export function sensor(x:Ctx,{scale=.64,noise=12,scan=.045,bleed=.055,tear=false,seed=14,vignettePower=.6}:SensorOpts={}){const W=x.canvas.width,H=x.canvas.height,[small,s]=mk(Math.round(W*scale),Math.round(H*scale));s.drawImage(x.canvas,0,0,small.width,small.height);x.save();x.imageSmoothingEnabled=true;x.drawImage(small,0,0,W,H);x.restore();const [copy,k]=mk(W,H);k.drawImage(x.canvas,0,0);x.save();x.globalCompositeOperation='screen';x.globalAlpha=bleed;x.filter='blur(2px)';x.drawImage(copy,2,0);x.filter='blur(7px)';x.globalAlpha=.075;x.drawImage(copy,0,0);x.restore();const rr=rng(seed);for(let yy=0;yy<H;yy+=16)for(let xx=0;xx<W;xx+=16){const v=rr();if(v<.14)rect(x,xx,yy,16,16,v<.07?'rgba(0,0,0,.018)':'rgba(185,202,206,.012)');}if(tear){for(const yy of [Math.round(H*.32),Math.round(H*.71)]){x.save();x.globalAlpha=.16;x.drawImage(copy,0,yy,W,2,3,yy,W,2);x.restore();}}if(bleed){const im=x.getImageData(0,0,W,H),p=im.data,src=new Uint8ClampedArray(p);const mix=Math.min(.48,bleed*5);for(let y=0;y<H;y++)for(let xx=2;xx<W-2;xx++){const i=(y*W+xx)*4;p[i]=src[i]*(1-mix)+src[i-8]*mix;p[i+2]=src[i+2]*(1-mix)+src[i+6]*mix;}x.putImageData(im,0,0);}grain(x,W,H,noise);if(scan)for(let y=0;y<H;y+=3)rect(x,0,y,W,1,`rgba(0,0,0,${scan})`);vignette(x,W,H,vignettePower);}
